### ISSUE TITLE
Schematic wrong pinout

### ISSUE THREAD

**Issue by uavmax** [sparkfun/Qwiic_Spectral_Sensor_AS7265x#1]
[https://cdn.sparkfun.com/assets/3/b/0/3/e/Qwiic_Spectral_Sensor-AS7265x.pdf](url)
SCL_M and SDA_M are not 1,20(SLV1_RESN, SLV2_RESN) pins but 9,10.
no ADDR, CS_SD pins just CSN(CD_EE). INT pin 13 not 9

**Comment by nseidle** [comment]
There has been a lot of confusion created by AMS because they released early datasheets that showed incorrect pinouts. I believe those are the datasheets you are looking at. Please see the notes on the documents tab of our [product page](https://www.sparkfun.com/products/15050). Namely:

Datasheets:

* [AS7265x](https://cdn.sparkfun.com/assets/c/2/9/0/a/AS7265x_Datasheet.pdf) (Pin assignments are misleading; use Design Considerations below.)
* [Design Considerations](https://cdn.sparkfun.com/assets/8/5/f/0/3/AS7265x_Design_Considerations.pdf)
